CREATE OR ALTER PROCEDURE TopSuppiler
	@Month INT
AS

SELECT S.Name,ROW_NUMBER() OVER(ORDER BY COUNT(S.SupplierID) DESC)
FROM Supplier S
INNER JOIN BookForSale BFS ON BFS.SupplierID = S.SupplierID
INNER JOIN Sales Sa ON Sa.BookForSaleID = BFS.BookForSaleID
WHERE BFS.Avalible = 0 AND Sa.DatePurchased BETWEEN  DATEADD(MONTH, -@Month, GETDATE()) AND SYSDATETIMEOFFSET()  
GROUP BY S.Name
GO
