CREATE OR ALTER PROCEDURE PopularGenre
AS
SELECT COUNT(B.GenreID)SalesCount ,ROW_NUMBER()OVER(ORDER BY COUNT(B.GenreID) DESC)AS GenreRank,G.Genre
FROM Sales S
INNER JOIN BookForSale BFS ON BFS.BookForSaleID = S.BookForSaleID 
INNER JOIN Book B ON B.BookID =BFS.BookID
INNER JOIN Genre G ON G.GenreID =B.GenreID
WHERE S.DatePurchased BETWEEN DATEADD(YEAR, -1, GETDATE()) AND SYSDATETIMEOFFSET()  
GROUP BY G.Genre
ORDER BY GenreRank
GO