--DROP  Table
DROP TABLE IF EXISTS Sales
DROP TABLE IF EXISTS BookForSale
DROP TABLE IF EXISTS Book
DROP TABLE IF EXISTS Condition
DROP TABLE IF EXISTS Genre
DROP TABLE IF EXISTS Buyer
DROP TABLE IF EXISTS Supplier